version: '3.8'

services:
  search-api:
    build:
      context: search/api
    ports:
      - "5050:5050"
    environment:
      - MLAPI_BASE_URL=localhost:5070
      - ES_CONN_STR=http://host.docker.internal:9200
      - REDIS_RESULTS_CONN_STR=redis://host.docker.internal:6379/0
    depends_on:
      - ml-api

  crawler:
    build:
      context: search/crawler
    environment:
      - ES_CONN_STR=http://host.docker.internal:9200
      - REDIS_CRAWLER_CONN_STR=redis://host.docker.internal:6379/1

  client:
    image: python:3.10.7-slim
    volumes:
      - ./search/client:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - search-api
    command: python3 -m http.server 8000 --directory /app

  ml-api:
    build:
      context: search-analytics/mlapi
    ports:
      - "5070:5070"
    environment:
      - POSTGRES_URI=postgresql://engine_user:engine_pass@host.docker.internal:5432/engine  # TODO: username password might be set better

  pipeline:
    build:
      context: search-analytics/pipeline
    environment:
      - MLAPI_BASE_URL=localhost:5070
      - PIPELINE_RUN_PERIOD=300
      - REDIS_RESULTS_CONN_STR=redis://host.docker.internal:6379/0
    depends_on:
      - ml-api

networks:
  default:
    name: transport
    external: true
